// <auto-generated />
namespace WebApp472.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identityinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityinit));
        
        string IMigrationMetadata.Id
        {
            get { return "202204181331339_identity init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
